name: GoldenDaysPetServicesTest
favicon: null
layout_spectrum: 0.26529
typography_spectrum: 0.53507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dad9de'
    - '#0c0401'
    - '#5079d3'
    - '#87591d'
    - '#f9b550'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
