name: GoldenDaysPetServicesTest
favicon: null
layout_spectrum: 0.9311215854249895
typography_spectrum: 0.12540055043064058
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.634037664392963
  lightness: 0.7236923680175096
  saturation: 0.9556319520343095
  rhythmicContrast: 0.38201691885478795
purpose: []
