favicon: null
name: GoldenDaysPetServicesTest
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5767285
  brandStrength: 0.5
  lightness: 0.7183811
  brandColors:
    - '#dad9de'
    - '#0c0401'
    - '#5079d3'
    - '#87591d'
    - '#f9b550'
  rhythmicContrast: 0.7369308
typography_spectrum: 0.5059022
layout_spectrum: 0.4890388
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
